name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install and build
        env:
          # These values are used for auto updates signing
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm run postinstall
          npm run build
          npm run package
